### ISSUE TITLE
Odd job gui

### ISSUE THREAD

**Issue by benisbabe** [Pemigrade/Acorn#100]
**Brief Description**
I think it would be cool if there was a GUI kind of like /ah where people can list odd jobs they need done and can pay people to do. 

**Why do you want the feature?**
Lots of people seem to be looking for stuff to do on the server and it would be a cool way to make money!

**Comment by Gottiii** [comment]
Kinda like Yellow Pages or Craigslist, this would be really useful in my opinion

**Comment by Pemigrade** [comment]
Is there a plugin that does this?

**Comment by Pemigrade** [comment]
Feature Request denied due to the lack of a compatible plugin. It can be reopened if someone suggests a plugin that accomplishes this feature.
