### ISSUE TITLE
Colored Anvil Renames

### ISSUE THREAD

**Issue by Delight-eats-cheese** [Pemigrade/Acorn#101]
**Brief Description**
When you rename items in an anvil with color codes in front, it applies the color

**Why do you want the feature?**
It gives users the opportunity to customize their items and have even more fun.

**Additional context**
I programmed a plugin that does that, ill DM you the .JAR on discord.

**Comment by vinceingithub** [comment]
this could be cool

**Comment by vinceingithub** [comment]
Can this be closed since this was added to a donation group?

**Comment by Pemigrade** [comment]
Premium donors can now rename items to colored names in anvils
