### ISSUE TITLE
Weeping and warped vines from bone mealing don't create a continuous vine

### ISSUE THREAD

**Issue by LatteOnGithub** [Pemigrade/Acorn#102]
**Describe the bug**
Using bone meal on the nether vines doesn't work as intended. (right side of images)

**Expected behavior**
Left side of images, made by using bone meal in a single-player world, on the server only by placing vines by hand.

**To Reproduce**
Bone meal warped or weeping vines, seems to be most consistent when only targeting the source attached to a block. Less common on warped.

![Weeping](https://user-images.githubusercontent.com/68391310/88334402-62f14e00-cd3a-11ea-875b-c59ecf7cc190.png)
![Warped](https://user-images.githubusercontent.com/68391310/88334407-6389e480-cd3a-11ea-91f1-30cd8e432799.png)

**Comment by Pemigrade** [comment]
Does this problem occur on vanilla 1.16.1?

**Comment by LatteOnGithub** [comment]
Does not.

**Comment by LatteOnGithub** [comment]
Should be fixed in 1.16.2 with [https://bugs.mojang.com/browse/MC-171739](url) even though the way it's created is different.

**Comment by LatteOnGithub** [comment]
Tested and fixed.
