### ISSUE TITLE
the PMC listing for Acorn still uses the old server banner

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#104]
**Description**

The cover image for Acorn on PMC is still the old server banner, not the new one made for 1.16

**Comment by Pemigrade** [comment]
PMC has an annoying verification process that forces me to do global /kick twice, and sometimes more if it messes up. It messes up at least 50% of the time. I think it's best to wait until the banner is further modified and updating the listing is more urgent.

**Comment by kakduman** [comment]
We don't really use PMC anymore
