### ISSUE TITLE
Make the quiz work

### ISSUE THREAD

**Issue by Pemigrade** [Pemigrade/Acorn#11]

**Comment by vinceingithub** [comment]
merge with #87 ?

**Comment by Pemigrade** [comment]
No. This is for the tutorial quiz, the other is for the book

**Comment by vinceingithub** [comment]
Right, I just assumed we were either doing a book or a quiz; not both. And it seemed that we were leaning to the book which is why I said that.

**Comment by Pemigrade** [comment]
Yep! Book will be given to everyone. This is just to make the quiz work, not to force all newbies to do it.

**Comment by Pemigrade** [comment]
Quiz has been permanently removed with the planned introduction of Gotti's spawn
