### ISSUE TITLE
Add Bedrock Support to the Existing Server

### ISSUE THREAD

**Issue by bennyman123abc** [Pemigrade/Acorn#110]
**Brief Description**
Add Bedrock support to the server with a plugin known as [GeyserMC](https://github.com/GeyserMC/Geyser) and [Floodgate](https://github.com/GeyserMC/Floodgate).

**Why do you want the feature?**
Opening up the server to Minecraft Bedrock Edition allows more players to be able to play on Acorn, and allows existing members to join the server on devices other than their PC (Game console, or mobile phone, for example).

**Additional context**
The plugins can be found at the following links:
- https://github.com/GeyserMC/Geyser
- https://github.com/GeyserMC/Floodgate

A video showcasing a Bedrock Client connecting (On a Geyser standalone server) can be found here:
- https://www.youtube.com/watch?v=Wl8hUMZaq34

**Comment by entwastaken** [comment]
i am really curious as to how this plugin deals with technical differences such as how redstone works, i.e QC

**Comment by Pemigrade** [comment]
It just converts Java packets. Bedrock players uses all Java mechanics. Some aspects of the game, like steps, work differently in Java and Bedrock. So, walking up steps may be glitchy as the server tries to enforce Java mechanics on Bedrock players.

**Comment by Pemigrade** [comment]
On hold until we switch hosts so that I don't have to deal with re-allocating ports

**Comment by HannahOnGithub** [comment]
Look bro, I just wanna play on acorn whenever I’m out of my house and have WiFi so… how do I upvote this shit?

**Comment by Pemigrade** [comment]
I actually started on this earlier today. I don't have bedrock so I can't check. If anyone can try connecting and let me know if it throws an error, it'd be very helpful

**Comment by Pemigrade** [comment]
Works when connected to direct IP but not through TCPShield, further testing required.

**Comment by HannahOnGithub** [comment]
Pemi btw I’m able to join acorn on pe now bc of bens wonders

**Comment by Pemigrade** [comment]
Weird, wasn't working for Apple. Could @bennyman123abc please try it and let me know if it works?

**Comment by HannahOnGithub** [comment]
Well it works for me but idk abt anyone else

**Comment by Pemigrade** [comment]
GeyserMC is incompatible with TCPShield. We may be unable to add it.

**Comment by Pemigrade** [comment]
Temporarily denied until TCPShield updates to allow the ports that GeyserMC uses to connect (127.0.0.1 or 192.168.2.x) or finds another way to allow GeyserMC connections

**Comment by bennyman123abc** [comment]
Read the config file. You can allow GeyserMC to listen on 25565, along with the Java server.

**Comment by Pemigrade** [comment]
I talked to both the GeyserMC team and the TCPShield team a few days ago. GeyserMC says that the plugin is incompatible with TCPShield unless you allow non-proxy connections in the TCPShield config. TCPShield has a commented line in their config warning that allowing non-proxy connections makes the server vulnerable to scanners who can find the backend IP and DDoS the server.

According to TCPShield, the solution is to only allow connections to the machine from TCPShield's proxies, Cloudflare's proxies, and reserved IPs.

**Comment by bennyman123abc** [comment]
I'm about to DM you with another solution I came up with regarding this issue. I would like to keep that to DMs as I'll be mentioning information regarding one of my VPS servers.

**Comment by Ashchu117** [comment]
> I talked to both the GeyserMC team and the TCPShield team a few days ago. GeyserMC says that the plugin is incompatible with TCPShield unless you allow non-proxy connections in the TCPShield config. TCPShield has a commented line in their config warning that allowing non-proxy connections makes the server vulnerable to scanners who can find the backend IP and DDoS the server.
> 
> According to TCPShield, the solution is to only allow connections to the machine from TCPShield's proxies, Cloudflare's proxies, and reserved IPs.
> 
> I'll try doing what you said and see if that's another way to go about it!

did you get it to work? just setup TCPShield and I'm having issues with Geyser as well now

**Comment by Pemigrade** [comment]
We don't use TCPShield anymore.

But to answer your question, TCPShield does NOT support Geyser if you're using TCPShield as a plugin. Well, technically it does. You just have to pay $25/mo on it.
