### ISSUE TITLE
Birdflop legacy color perks do not work as intended

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#112]
**Describe the bug**

It appears that Birdflop people who have perms for one color but not all colors are having issues using the colors that they have perms for.

**Expected behavior**

Using the color code for a legacy color perm should allow you to use it.

**Comment by Pemigrade** [comment]
Due to constantly changing chat plugins, maintaining Birdflop legacy perks takes far more time than it's worth. I don't think I'll ever get around to this issue, so I'm denying it.
