### ISSUE TITLE
Mods and most Admins cannot start/restart the server

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#114]
**Describe the bug**

In some cases people like myself can see some of the servers but cannot do anything with them, or in cases like Taco's some have no access at all; but in all cases most admins/mods can't start/restart the server. It seems like the only people who can atm are Pemi, Bot, Ollie, and maybe Sonic.

**Comment by Pemigrade** [comment]
This is intentional. Please read https://discordapp.com/channels/354802944354418688/481172382078468107/730175465498869811. If you do not have 2FA enabled or have not informed me that you enabled it, you cannot access the server panel.
