### ISSUE TITLE
Add basalt, blackstone to list of blocks that despawn only 30 seconds after being tossed on the ground.

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#115]
**Brief Description**

There's a list of blocks that despawn after only 30 seconds on the ground, including cobblestone and netherrack. This is done to avoid lag.

**Why do you want the feature?**

I know especially for me, I leave behind trails of basalt and blackstone in the nether when I strip mine and all of those extra entities can create unneeded lag.

**Comment by Pemigrade** [comment]
Done
