### ISSUE TITLE
Hostile mobs that go through portals despawn

### ISSUE THREAD

**Issue by LatteOnGithub** [Pemigrade/Acorn#117]
**Describe the bug**
When any hostile mob goes through a nether (likely also end) portal and there is no player on the other side the mob despawns immediately.

**Expected behavior**
Mob to stay in the nether and keep it loaded for 15s like in a vanilla world.

**To Reproduce**
Get a mob to go through a portal and go in after it.

**Comment by Pemigrade** [comment]
This is intentional. Monsters despawn immediately on Acorn if the chunk is not loaded. You can ask another player to wait on the other side of the portal to keep that chunk loaded while you transport the mob(s).
