### ISSUE TITLE
Add the ability to convert nether wart blocks into normal nether wart / Avsom's Suggestion

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#118]
**Brief Description**

Add the ability to convert nether wart blocks into normal nether wart using a crafting table.

**Why do you want the feature?**

"I would like to see additional means of acquiring nether wart, because once all of the fortresses have been raided, you're SOL....as of two weeks ago, only two shops were selling nether wart, and one of them was out of stock." -Primustheone

**Additional context**

A datapack for this feature can be easily made using: https://crafting.thedestruc7i0n.ca/

**Comment by Pemigrade** [comment]
Done! Restart required
