### ISSUE TITLE
Creative: Players can worldedit anywhere within the creative spawn

### ISSUE THREAD

**Issue by excyrlia** [Pemigrade/Acorn#121]
**Describe the bug**
Players with worldedit access can use it to paste, cut, copy etc. inside the spawn area in the creative server.

**Expected behavior**
they really shouldn't be able to do that ideally

**To Reproduce**
-1. just like, ask me to do it and i'll show you it works
0. ok fine, so
1. be a non-staff member
2. have worldedit access
3. select two points in spawn via [//wand]
4. type [//set glass]
5. observe the glass

**Additional context**
yes i did use this but in a, frankly, non-harmful way (https://i.imgur.com/j37BR32.png). people can essentially just delete spawn if they want to

**Comment by Pemigrade** [comment]
No
