### ISSUE TITLE
Add Hero of the Village potions to the rare crate

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#123]
**Brief Description**

Add potions which grant the effect "Hero of the Village" to the rare crate.

**Why do you want the feature?**

It is a very valuable effect so it makes sense that it would be balanced by being locked to the rare crate.

**Additional context**

/minecraft:give @p minecraft:potion{Potion:"minecraft:water",CustomPotionEffects:[{Id:32,Duration:6000}],display:{Name:""Hero of the Village Potion""}}

**Comment by entwastaken** [comment]
i don't agree with adding this, because it would make raids basically obsolete for the average player

**Comment by vinceingithub** [comment]
I see your point, however, rare crate keys are rare enough and this items drop chance would be rare enough that it would have no affect on the average player. Also: the time till expiry of this potion would be vastly quicker than actually getting HOTV.

**Comment by Pemigrade** [comment]
Merged with #119
