### ISSUE TITLE
Rare crate player heads drop apples

### ISSUE THREAD

**Issue by IcyGrillz** [Pemigrade/Acorn#125]
**Describe the bug**
When receiving the player head item from a Rare Crate, an apple is dropped

**Expected behavior**
When receiving the player head item from a Rare Crate, the player's head is dropped

**To Reproduce**
1. go to the rare crate
2. Obtain player head as reward (custom skin)

**Additional context**

**Comment by vinceingithub** [comment]
The player head that was obtained appears to be correct, issue may be client side. Further investigation needed.

![image](https://user-images.githubusercontent.com/50550001/89177040-9f9e2000-d558-11ea-8775-7455e6880a34.png)

**Comment by vinceingithub** [comment]
The issue turns out to be with the entire crates system itself, not a huge issue but when opening rare crates you sometimes get an apple, not an apple head you just get a random apple after you get what you rolled. A fix is low priority.

**Comment by IcyGrillz** [comment]
Screenshot below
![2020-08-03_07 17 56](https://user-images.githubusercontent.com/69148392/89177621-df193c00-d559-11ea-8f8b-a669a6d27465.png)

**Comment by Pemigrade** [comment]
Haha, this is kind of funny. The crate plugin defaults to giving an apple when you add a new reward, so I have to manually remove the apple from each item. It doesn't affect anything, it just gives a free apple. I guess I forgot to remove it on this one!
