### ISSUE TITLE
Expand the amount of information in #faq / Ehlyo's Suggestion

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#126]
**Brief Description**

"I was thinking add more info in it, piglin for example has a lot of info, like a link to the website, how to ban appeal, where to donate, info about ranks..." -Ehlyo

**Why do you want the feature?**

"...i know most of these are accessed from the website but it would be nice to just be able to click and already be where you wanna be" -Ehlyo

**Text Submissions**
To make this easier on pemi, if anyone cares to type out this information so that he doesn't have to please do so and comment it on this feature request.

**Comment by Pemigrade** [comment]
#13 is a prerequisite

**Comment by Pemigrade** [comment]
Done!
