### ISSUE TITLE
Resource Collection

### ISSUE THREAD

**Issue by LordServek** [Pemigrade/Acorn#127]
Have a spot that has regenerating sand/dirt/gravel

As it is, people have to destroy the world to get massive amounts of resources.  These 3 things are not "expensive" and are major needed items to make other items. 

This was a feature on a site that I was an Admin on. Each area was a 16x16x16 pit, that had a ladder inside one wall.  At the top of each area was a button.  When you pressed the button it just refilled the pit with either the gravel/sand/dirt/  The walls of the pits were made out of bedrock so they could not be damaged.   This really helped the overworld not get destroyed on a regular basis.

**Comment by vinceingithub** [comment]
A resource world would work better.

**Comment by Pemigrade** [comment]
@LordServek Why is a resource world insufficient?
