### ISSUE TITLE
Create acornmc.org/ranks

### ISSUE THREAD

**Issue by Pemigrade** [Pemigrade/Acorn#13]

**Comment by vinceingithub** [comment]
If need be I can type up the text for the webpage to make it easier for you.

**Comment by Pemigrade** [comment]
That would be helpful, use https://piglin.org/ranks as a model of what it should look like. Make sure to reference #18 and the current rank rewards at /warp ranks when creating it please

**Comment by vinceingithub** [comment]
All done! https://docs.google.com/document/d/1e8Oq4NfBjNSWb4SyFrxMiDy71tDqGjP3nnA2K1f489U/edit?usp=sharing

**Comment by Pemigrade** [comment]
Thanks vince! Was very helpful while creating the webpage
