### ISSUE TITLE
Sabotage: If possible, scale Insight limit with playercount

### ISSUE THREAD

**Issue by entwastaken** [Pemigrade/Acorn#132]
**Brief Description**
If possible, scale the amount of Insights the Detective can buy to the amount of players in the game.

**Why do you want the feature?**
When there are too few players (5 or less), 3 Insights makes it too easy to find the Saboteur because, even on 5 players, he can Insight 3 players and, worst case scenario, all of them are Innocents, weeding out the Saboteur without any major effort. When there are too many players (say, 10), the Detective can only check 3 out of 9 players, and if all of them are Innocents, then the Detective simply wasted 180 karma.

**Additional context**
insight's stupidly op

**Comment by EaglePrideMC** [comment]
An option to scale the maximum number of times the detective can insight other players has been added to Sabotage version 1.2.9.

I will add, though, that insight is not suppose to be a very helpful tool for the detective in large games. Insight was designed to be used if the saboteur stops attacking other players at the end of a round and the detective cannot identify what player is the saboteur.
