### ISSUE TITLE
Chest Shop "?" Bug

### ISSUE THREAD

**Issue by iJoaRL** [Pemigrade/Acorn#134]
**Describe the bug**
 Chest shop removes sign when a "?" is placed on the bottom sign

**Expected behavior**

When you put a "?" in the last line you can then click the sign with an item and it uses the correct item code to sell/buy.
**To Reproduce**
1. Go to chest
2. Click on sign
3. Scroll down to last line and "?"

**Additional context**

**Comment by Pemigrade** [comment]
Resolved!
