### ISSUE TITLE
Sabotage: Unable to replace water blocks in build mode

### ISSUE THREAD

**Issue by Pemigrade** [Pemigrade/Acorn#137]
**Describe the bug**
I can't place a block where water currently is while in mod mode and after doing /startbuild. It does not matter if it's a source block or if the water is flowing.

**Expected behavior**
I should be able to replace the water blocks

**To Reproduce**
1. Type /mod.
2. Type /startbuild Modern Paris.
3. Place a water bucket down.
4. Try to place a stone brick down where the water is.
5. Observe error.

**Additional context**
Low priority since I can //replacenear 2 water air and then re-add the water blocks.

**Comment by EaglePrideMC** [comment]
I could not replicate the issue on Sabotage version 1.2.8, but it was present in older versions. Closing this issue since the problem seems to be solved.
