### ISSUE TITLE
Make /wild work in the nether

### ISSUE THREAD

**Issue by quervy** [Pemigrade/Acorn#138]
**Brief Description**
When you are in the nether and you run the /wild or /rtp command, you will teleport to a random place in the nether.

**Why do you want the feature?**
People mine a lot for netherite and it will be easier to find unmined areas in the nether.

**Comment by Pemigrade** [comment]
Done!

**Comment by Pemigrade** [comment]
Oh, I forgot to mention that you'll need to use /rtp nether instead of just /rtp.
