### ISSUE TITLE
Sabotage: Taco's idea: Add a chance for two detectives, one of whom is actually a sab.

### ISSUE THREAD

**Issue by EaglePrideMC** [Pemigrade/Acorn#146]
**Brief Description**
The detective is normally the "leader" of the innocent team. Add a small chance for there to appear to be two detectives, but one of the detectives is actually a saboteur.

**Why do you want the feature?**
It could add another dimension to the game.

**Comment by vinceingithub** [comment]
I don't think that this is a good idea. It will just lead to innos RDMing the Detective, if the innos can't even trust the detective then it ruins the entire point of the role.

**Comment by Pemigrade** [comment]
It'd also be worse for the saboteur since they can be narrowed down to one of two people. I think I'm going to deny this one.
