### ISSUE TITLE
New Auction House

### ISSUE THREAD

**Issue by GHAppleMan** [Pemigrade/Acorn#148]
**Brief Description**
An auction house that actually functions as an auction house, not as a marketplace.

**Why do you want the feature?**
This plugin will allow players to actually auction things using a GUI rather than only selling them for a set price. In the future we won't need to do auctions through the Minecraft chat or voice chats.

**Additional context**
After doing some research, it looks like https://www.spigotmc.org/resources/auctionmaster-1-8-8-1-16.76072/ would be a fantastic plugin to use, as it allows players to set custom bids and use the GUI to search for specific items or types of items. The plugin can also utilize citizens to have custom player models used to open the Auction House. On top of that, an add-on plugin https://www.spigotmc.org/resources/auctionmasteritemdisplay-addon.79002/ would allow us to have physical representations of the top auction positions, which could be great added to the spawn (or as a separate warp).

**Comment by vinceingithub** [comment]
This would have to be added alongside /ah not replacing the /ah.

**Comment by Pemigrade** [comment]
alternative proposed by Lefty:
https://www.spigotmc.org/resources/trade-system-custom-layouts.58434/

**Comment by kakduman** [comment]
This gets suggested a lot and is more of a #suggestions thing right now
