### ISSUE TITLE
New minigames on acorn (cocorobot3’s suggestion)

### ISSUE THREAD

**Issue by HannahOnGithub** [Pemigrade/Acorn#150]
**Brief Description**
New mini games to be added on acorn. 

**Why do you want the feature?**
I just think it could be fun, it could bring in more people to play it too. Just having sab is kinda a bummer considering the community here mainly is here for survival.

**Additional context**
A new mini game like a waves would be a fun chance to bring in more people.

**Comment by Pemigrade** [comment]
This is a lot of work and I don't think I'll ever get around to it, but I'll mark it as On Hold

**Comment by kakduman** [comment]
closing for above reason
