### ISSUE TITLE
Make people auto-respawn at /warp pvp on death / agf3ms' suggestion

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#151]
**Brief Description**

Make it so that when people die at /warp pvp, they respawn in the warp's safezone.

**Why do you want the feature?**

It can be annoying to have to warp back constantly.

**Comment by Pemigrade** [comment]
It looks like the plugin is broken. I can't fix it, but I can try to report it to the dev.

**Comment by Pemigrade** [comment]
Done! Credit to Sonic for thinking to set the flag for the spawn region instead of the pvp region
