### ISSUE TITLE
/claimflag noenterplayer staff can be banned

### ISSUE THREAD

**Issue by iJoaRL** [Pemigrade/Acorn#152]
**Describe the bug**

When you do the command /claimflag noenterplayer staff can't enter that claim even if they force tp
**Expected behavior**

Staff should be able to get into
**To Reproduce**
1. Go to claim
2. Type /claimflag noenterplayer (name)
3. Then Staff force tp

**Additional context**

**Comment by Pemigrade** [comment]
Helper+ can do /ignoreclaims or /ic to be immune to noentry claim flags when necessary
