### ISSUE TITLE
/keys shows the old username

### ISSUE THREAD

**Issue by ehylo** [Pemigrade/Acorn#154]
**Describe the bug**

Awhile back I changed my (alt's) username from Wamtequilla to BlamePaper and when I do /keys it shows my old username.

**Expected behavior**

It should be showing BlamePaper not Wamtequilla when I do /keys.

**To Reproduce**
1. Vote for the server and do /keys
2. Change your minecraft username
3. Vote again with the new username
4. Do /keys in game and see that it will show the old username

**Additional context**
![Capture](https://user-images.githubusercontent.com/48396713/91204815-7422d700-e6b9-11ea-9ba1-c56b453d5141.PNG)

**Comment by Pemigrade** [comment]
Interesting, I'll try to reproduce this on an alt and inform the GoldenCrates dev about the issue

**Comment by kakduman** [comment]
we no longer use goldencrates
