### ISSUE TITLE
Nether brick block slab crafting

### ISSUE THREAD

**Issue by LatteOnGithub** [Pemigrade/Acorn#155]
**Describe the bug**
**To Reproduce**
![Screenshot_31](https://user-images.githubusercontent.com/68391310/91360736-ad655f00-e7ff-11ea-98ef-a607c1cc4828.png)

**Expected behavior**
Make nether bricks block

**Additional context**
You just need to add an S. nether_brick > nether_bricks

**Comment by Pemigrade** [comment]
Done
