### ISSUE TITLE
Adding /trade

### ISSUE THREAD

**Issue by HannahOnGithub** [Pemigrade/Acorn#156]
**Brief Description**
/trade would be good for when people want to trade something say for example 3 wither skulls for a beacon

**Why do you want the feature?**

I think it would be neat
**Additional context**

**Comment by Pemigrade** [comment]
Why can't people just /tpa and trade the items? There are very few instances of people being scammed, and people who are scammed can easily be given their items back and the scammer banned. "it would be neat" just isn't a very compelling reason to add this feature.
