### ISSUE TITLE
Pin Color Codes on Discord to #global

### ISSUE THREAD

**Issue by Acousti** [Pemigrade/Acorn#161]
**Brief Description**
Pin a picture of the color codes in #global

**Why do you want the feature?**
Mostly for ease of access so people don't have to look it up on google each time

**Additional context**
Here's a picture: 
![image](https://user-images.githubusercontent.com/72317458/94999605-7b76b380-0588-11eb-8fbc-3afbeb4d34ea.png)

Also, here's text if thats easier (organized by brightness):
**Dark Colors**
&0 = Black
&1 = Dark Blue
&2 = Dark Green
&3 = Dark Aqua
&4 = Dark Red
&5 = Dark Purple
&8 = Dark Gray

**Med Colors**
&6 = Gold
&7 = Gray
&9 = Blue

**Light Colors**
&a = Green
&b = Aqua
&c = Red
&d = Light Purple
&e = Yellow
&f = White

**Other**
&l = Bold
&n = Underline
&o = Italic
&m = Strikethrough
&k = Magic
&r = Reset

**Comment by Pemigrade** [comment]
Done, I did not add formatting.
