### ISSUE TITLE
Add a Debate Channel?

### ISSUE THREAD

**Issue by Acousti** [Pemigrade/Acorn#165]
**Brief Description**
This is a channel where things like politics and sensitive topics can be discussed. Toxicity, hate speech, spam, and flame wars would still not be allowed and would result in loss of access to this channel. (Also I just wanna note that if this did become a thing, the rules wouldn’t have to be exactly as I just described, it could end up having the exact same set of rules acorn usually has, but just a place to debate certain suggestions/polls and things like that).
*-LeftyIsHere*

**Why do you want the feature?**
A lot of people discuss/debate abt stuff that some may find interesting and others may find annoying, these discussions can be taken to the debate channel, and ppl could just mute the channel if it's annoying 
*-PureBasic*

**Additional context**
#bringbackdiscussions&debates
*-ConarLemon*
Although this may not have worked too well before, it may be a good idea to give it a second chance with a new community. With a new set of rules and options to exclude yourself from seeing the channel, it will probably turn out better than before. I think it should be at least reconsidered, or given a trial period.
*-AcoustiXkey*
I suggested that Discussions be a rank that players get and the discussions rank could get removed from a toxic player who breaks discussion rules. An issue before when we had #debates. ppl kept telling the "debaters" to calm down or stop the conversation or continue it in DMs. that was annoying. 
*-PureBasic*
Also, it could be a dyno role or something so u have to do ?debate to get it, so people who don’t want to be involved wouldn’t have to be
*-LeftyIsHere*

**Comment by Pemigrade** [comment]
The old channel was deleted due to inactivity. Use #suggestions for debates please!
