### ISSUE TITLE
Sabotage: Detonator does not work

### ISSUE THREAD

**Issue by Pemigrade** [Pemigrade/Acorn#166]
**Describe the bug**

The detonator does not work after being purchased in the /shop

**Expected behavior**

The detonator should work...

**To Reproduce**
1. Go to /sabotage
2. Wait for a round to start and purchase the nuke
3. Try to use the detonator.

**Comment by EaglePrideMC** [comment]
Resolved – there was an issue with the Sabotage config file that should be fixed now. Sabotage will need to be reloaded or the server restarted for this fix to come into effect.
