### ISSUE TITLE
New Crate Idea

### ISSUE THREAD

**Issue by cocorobot3** [Pemigrade/Acorn#168]
**Brief Description**
A new crate type would be cool. “Legendary Crate Key” has a ring to it, ya know

**Why do you want the feature?**
Uh I really don’t know, I think rarer items rather than the rare crate would be cool. We could move around some of the items from rare crates into here?

**Additional context**
The legendary crates would have things like the rare crates, but a little different.. like for example, an acorn banner (it has more than 6 textures so this is creative found only, maybe make it unduplicable or something) And like 10k coins, and maybe even have it give netherite and stuff. Or maybe sharpness 6? And maybe like a splash potion of lighting (5 lightning bolts) And maybe like Untextured blocks maybe? (I LOVE untextured blocks pls...) And maybe like certain donor only things or stuff like the glow effect (someone suggested this earlier) or like you get text color for a week or something. Or maybe like 10 rare crate keys? Idk these ideas aren’t in stone but this would be cool? Also, even tho this doesn’t sound vanilla, I mean, is this server even that vanilla anymore?

**Comment by Pemigrade** [comment]
This sounds like the epic crate. I might be able to add some of these to the epic crate, but I don't see a need for a new crate.
