### ISSUE TITLE
Flying in Pvp

### ISSUE THREAD

**Issue by MrMalware0** [Pemigrade/Acorn#170]
**Describe the bug**
People can use /fly in Pvp zones

**Expected behavior**
um get it fixed i guess but take your time Pemi

**To Reproduce**
1. One of the Pvp zones
2. type /fly
3.  poof you can fly and you shouldn't be able to
4. idk what to put here

**Additional context**
this is confusing just people can fly in pvp and idk how or why sorry this probably doesn't help

**Comment by Pemigrade** [comment]
Resolved for all new PvP arenas. Existing ones may need to be updated.
