### ISSUE TITLE
[Sabotage] Water tends to block right click functions

### ISSUE THREAD

**Issue by entwastaken** [Pemigrade/Acorn#172]
**Describe the bug**
Being underwater(or sometimes just in 1-block deep water or even simply near water) seems to block the ability to use right click for actions such as placing TNT or equipping armour. (note: Lefty informed me about the TNT, i haven't tested it myself, but i know 100% that the armour bug is caused by this)

**Expected behavior**
Water should not affect right clicking.

**To Reproduce**
1. Join a game on a map such as Emerald Illusion
2. Get a piece of armour in your hand
3. Enter one of the waterfalls
4. Try equipping the armour using rightclick; it will only work for a few frames, then return to your hand.

**Additional context**
very frustrating bug 
note: this doesn't happen just to me, as i previously thought; lefty has had it happen to him as well, which confirms it isn't just a ping issue like i initially thought

**Comment by Pemigrade** [comment]
Able to reproduce

**Comment by EaglePrideMC** [comment]
Issue should now be solved.
