### ISSUE TITLE
[Website] Add a Hall of Fame

### ISSUE THREAD

**Issue by excyrlia** [Pemigrade/Acorn#173]
**Brief Description**
Add a Hall of Fame section to the website, which would display the names of certain players that are worthy of being mentioned for their achievements on the server.

**Why do you want the feature?**
It would be great to commemorate those who have made great contributions to the server, have been here since the beginning and are still active, or that have had a lasting impact on the community.

**Additional context**
its 3 am

**Comment by Pemigrade** [comment]
No. I'm not interested in spending the time on maintaining a decorative hall of fame in place of working on stuff that will actually help the server. There's also the issue of deciding the players who would be added to it / removed from it if necessary.
