### ISSUE TITLE
Display mute reasons to players who are muted

### ISSUE THREAD

**Issue by LeftyIsHere** [Pemigrade/Acorn#174]
**Brief Description**

Players should be given the permission node that allows them to see when they are muted, and why.
**Why do you want the feature?**

A lot of the time when some players are muted, they are confused and ask a staff member to explain for them what they were muted for. If mute reasons were shown to the player when they are muted, it would reduce confusion and conflict, and staff members wouldn't always have to explain a mute to the player.
**Additional context**

**Comment by Pemigrade** [comment]
done
