### ISSUE TITLE
If you don't log on daily then vote streaks don't count

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#175]
**Describe the bug**
Self explanatory, if you're like me and vote for days in a row and then log on it isn't considered a streak despite voting daily.

**Comment by Pemigrade** [comment]
Would have to be reported to votingplugin dev

**Comment by Pemigrade** [comment]
Should be fixed since we switched back to SOCKETS. If anyone wants to report to https://github.com/BenCodez/VotingPlugin/issues that PLUGINMESSAGING doesn't update votestreaks, feel free to give it a shot.
