### ISSUE TITLE
ban from claims

### ISSUE THREAD

**Issue by saboooor** [Pemigrade/Acorn#177]
**Brief Description**
ban from claims

**Why do you want the feature?**
it would provide some privacy for people who want it, or just ban specific players from claims if they're annoying

**Additional context**
https://www.spigotmc.org/resources/banfromclaim.70897/

**Comment by saboooor** [comment]
also add a command alias /claimban and /claimunban for some consistency given the fact that we have /shopban and /shopunban

**Comment by Pemigrade** [comment]
Updated https://ci.birdflop.com/jobs/GriefPreventionFlags to fix claim bans. Will be fixed after a restart.
