### ISSUE TITLE
Replace the message for ?link with "Please read #!read-me!" (or something like that)

### ISSUE THREAD

**Issue by Acousti** [Pemigrade/Acorn#178]
**Brief Description**
Replace the Linking message in ?link with one that displays the #read-me channel name so that it redirects the unlinked users to the channel (which shows the same thing as the current ?link) instead of havingthem read it in the general chat.

**Why do you want the feature?**
This feature would be nice because the current message in ?link is hella long and it clogs up the chat (Especially on mobile devices where the chat screen is smaller. Even on a computer, it's still a lot. This would also allow for people who don't have access to the #!read-me! channel to display the channel name without going through the process of putting in the exclamation point emojis.

**Additional context**
Possible messages are:
- Check out #!read-me! for discord help
- Go to #!read-me! to get information on linking your discord account
**It's important to include the channel name in the message**

**Comment by kakduman** [comment]
read-me is now more prominent, I think. It's also pretty easy to just type #read-me
