### ISSUE TITLE
Add GriefPreventionFlags and Give Ranks Additional Benefits

### ISSUE THREAD

**Issue by Pemigrade** [Pemigrade/Acorn#18]

**Comment by Pemigrade** [comment]
**GRIEF PREVENTION FLAGS**
AllowPVP - None for now, phantom+ later
KeepLevel - creeper+
EnterMessage - stray+
ExitMessage - spider+
HealthRegen - phantom+
InfiniteArrows - wither+
KeepInventory - wither+
NoChorusFruit - skeleton+
NoCombatLoot - none for now, phantom+ later
NoEnderPearl - skeleton+
NoEnter - wither+
NoEnterPlayer - phantom+
NoExplosionDamage - phantom+
NoFallDamage - wither+
NoFireDamage (New - (This is added, but make sure to enable FireDamage in the GP config))
NoFlight - spider+
NoFluidFlow - phantom+
NoGrowth - skeleton+
NoHunger - wither+
NoIceForm - stray+
NoItemDrop - phantom+
NoLeafDecay - skeleton+
NoMobDamage - wither+
NoMobSpawns - wither+
NoMonsterSpawns - wither+
NoSnowForm - spider+
NoVehicle - spider+
NoVineGrowth - skeleton+
PlayerTime - phantom+
PlayerWeather - phantom+
RaidMemberOnly - drowned+
RespawnLocation - stray+
SpleefArena - creeper+

**Comment by Sonic-Probe** [comment]
I can do this

**Comment by Pemigrade** [comment]
Permissions assigned, #33 is next step!
