### ISSUE TITLE
Show &7&lAFK or something after someone who is afks name in the tablist

### ISSUE THREAD

**Issue by LeftyIsHere** [Pemigrade/Acorn#180]
**Brief Description**
Show &7&lAFK or something after someone who is afks name in the tablist

**Why do you want the feature?**
So that ppl can see who is afk without having to do /list

**Additional context**
it would be pog and helpful

**Comment by Pemigrade** [comment]
agreed. If anyone wants to make a PR for it I'll accept it. Otherwise I'll keep it at low priority and won't get to it for a while. Added BungeeTabListPlus tabLists to the code tab.
