### ISSUE TITLE
Remove [/disguise] inside PvP arenas

### ISSUE THREAD

**Issue by entwastaken** [Pemigrade/Acorn#183]
**Brief Description**
Players shouldn't be able to use [/disguise] inside PvP arenas to change their model.

**Why do you want the feature?**
It is very disruptive - the Ender Dragon disguise is massive and constantly plays the Ender Dragon wings sound - and also very abusive, as the command also changes your hitbox, and certain models are semi-invincible - the Invoker's ground claw thing can only be hit by arrows. Tahani (CoolPanda53) abuses it a lot at [/warp pit].

**Additional context**
Screenshots of Tahani abusing it:
![2021-01-04_11 06 49](https://user-images.githubusercontent.com/37774796/103519205-ca7cff00-4e7d-11eb-8322-fa58cbabdab8.png)
![2021-01-04_11 09 30](https://user-images.githubusercontent.com/37774796/103519213-ce108600-4e7d-11eb-9d8c-42053312abc5.png)
(Yes, that arrow IS Tahani)

**Comment by Pemigrade** [comment]
additionally would need to undisguise players on entry

**Comment by Pemigrade** [comment]
Looks like we did this a fair bit ago.
