### ISSUE TITLE
Change in VIP vote perks

### ISSUE THREAD

**Issue by PureBasic** [Pemigrade/Acorn#184]
**Brief Description**
VIPs currently have the ability to disguise as a mob and as a player. I'm suggesting for it to be changed to only mobs. 

**Why do you want the feature?**
If a player can disagree with their name/nick being used by another person, I think the same should apply to disguises. 

**Additional context**
I just don't see a reason as to why a player should and could disguise as another player. And because it's not against the rule, that player can't be held accountable nor can they be told to stop.

**Comment by Pemigrade** [comment]
done
