### ISSUE TITLE
/nickname for discord

### ISSUE THREAD

**Issue by RealMoneyMalc** [Pemigrade/Acorn#185]
**Brief Description**
So I'm just looking for an official yes or no. Previously, the subject has been discussed but there wasn't really an answer to whether it was or wasn't going to be implemented. For the description: allow people with /nick ingame to use /nick on discord. Note: this does NOT mean linking the ingame nick to the discord, it just means giving players the /nick command on discord.

**Why do you want the feature?**
I think this feature would be nice to have on discord for those who got /nick from the voteshop/donating, just like how those who got /color have the ability to use the color codes in global.

**Additional context**
From the last discussion we had about /nick, DrBot said that this was possible except for the fact that people could pretend to be others. Also that it's harder to identify someone from discord. I think to make it easier there should be a set of rules made for the nickname command so it isn't misused.
Reference to the last response regarding my nickname suggestion: https://discord.com/channels/354802944354418688/540339402526818304/756000981967175712

**Comment by Pemigrade** [comment]
Official no. /nick on Discord makes it incredibly difficult to find someone. Unlike in-game, there's no Discord /realname command to find out a person's true identity.

It also breaks the bot by making it impossible to see your vnext and vtotal in #info
