### ISSUE TITLE
Restrict the bots to the #bots channel

### ISSUE THREAD

**Issue by Acousti** [Pemigrade/Acorn#186]
**Brief Description**
Only allow the commands for Dank Memer, MEE6, Idle Miner, Gambling Bot (+), OwO, TacoShack to be executed in the #bots channel, and Rythm and Rythm 2 to #bots and #voice.

**Why do you want the feature?**
This would stop people from mistakenly using the commands in non-bots-related channels.

**Additional context**
n/a

**Comment by kakduman** [comment]
I don't think this is a problem anymore. Seems ppl stopped using the bots as much
