### ISSUE TITLE
New Donation Pack Formats

### ISSUE THREAD

**Issue by AdmiralDandy** [Pemigrade/Acorn#189]
**Brief Description**
Split up all of the perk packages into smaller and cheaper packs, but also keep the large and complete packs.

**Why do you want the feature?**
This would give the ability to players who don't exactly have a lot of money to give support, and to more easily pick and choose which perks they may or may not want. Ultimately buying each Mini-Pack separate would be more expensive than buying the large packs with everything, so the players who decide to donate that want everything, still have the incentive to buy it all at once.

**Additional context**
The perks underlined with the same color are my idea for perks that would match into Mini-Packs, which of course is subject to change assuming this idea even gets accepted.

![Mini-Pack Format](https://user-images.githubusercontent.com/79222524/108254967-390dd780-7121-11eb-821e-50f76c491be8.jpg)

![Mini-Pack Format Cont](https://user-images.githubusercontent.com/79222524/108254976-3c08c800-7121-11eb-8329-fad095556015.jpg)

**Comment by Pemigrade** [comment]
Unfortunately, I'm extremely hesitant to change the format of donations since they keep Acorn afloat. This is the one area where I cannot consider major suggestions
