### ISSUE TITLE
RemovePlayer Claimflag for All! (minus zombies)

### ISSUE THREAD

**Issue by PureBasic** [Pemigrade/Acorn#191]
**Brief Description**
All players Husk+ should have the ability to remove a player from their claim using the removeplayer claimflag.

**Why do you want the feature?**
Some players intentionally like being a pain in the ass and refuse to leave someone's claim when asked to by the claim owner, and that player only leaves when a staff tells them to leave. If a staff member isn't on, that player probably wont leave the claim, and I don't think a player should have to endure another player's childish behavior until a staff member comes on. If players can shop ban another player, they should be able to yeet them off their claim too. :)

**Additional context**

**Comment by kakduman** [comment]
Closing due to /claimflag noplayerenter now being available
