### ISSUE TITLE
When you go to spawn it removes you from /nosleep

### ISSUE THREAD

**Issue by quervy** [Pemigrade/Acorn#192]
**Describe the bug**
When you add yourself to the nosleep list and go to spawn it removes you from the list.

**Expected behavior**
To not remove you from the nosleep list if you go to spawn

**To Reproduce**
1. Run command /nosleep
2. Go to /spawn
3. Now it removes you from the list

**Additional context**
Also happens when you go to the end or nether but i think thats on purpose

**Comment by entwastaken** [comment]
the reason why this happens is because [/spawn] is now in a separate world from the main survival world. think of it like how the nether and end are different dimensions, that's basically what is going on with [/spawn] too. therefore it is intended, albeit annoying.

**Comment by Pemigrade** [comment]
Bot might be able to fix this

**Comment by Pemigrade** [comment]
I'm told this is an intentional feature.
