### ISSUE TITLE
Fix the lighting in the spawn world

### ISSUE THREAD

**Issue by Voldechu** [Pemigrade/Acorn#193]
**Describe the bug**
Artificial lighting at /spawn broke, and now places like the maze and PvP arena are incredibly dark.

**Expected behavior**
These areas should have lighting in some form or another so you can see what you're doing.

**To Reproduce**
1. Go to spawn
2. Enter the maze
3. See error, or rather not see it as you can't see anything.

**Additional context**
Either torches or the old artificial lighting would work, just something is needed.

**Comment by Pemigrade** [comment]
Done
