### ISSUE TITLE
Give ArtKit to donors with ArtMap perms

### ISSUE THREAD

**Issue by Voldechu** [Pemigrade/Acorn#194]
**Brief Description**
Players with ArtMap are required to fetch their own dyes, when a person right clicks on a canvas, they should be able to have all the dyes/paints available to them from the get go. (Basically, Enable ArtKit)

**Why do you want the feature?**
Most dyes/colors are made of incredibly obscure and sometimes hard to get items, and it can be a great pain to gather said items for just that right shade of green you want. 

**Additional context**
n/a

**Comment by Pemigrade** [comment]
I think artmap no longer works. I'll definitely do it when/if we add it back, though.
