### ISSUE TITLE
Add EssentialsXDiscord

### ISSUE THREAD

**Issue by saboooor** [Pemigrade/Acorn#195]
**Brief Description**
Add EssentialsXDiscord, an official module for Essentials that allows for things Essentials-related in Discord

**Why do you want the feature?**
With this plugin, you can /msg people in-game from Discord

**Additional context**
You may have to do some config stuff to disable the DiscordSRV knockoff that EssentialsXDiscord has
Download link
https://discord.com/channels/390942438061113344/817518771233095741/829165225911648266

**Comment by kakduman** [comment]
Denying very low priority ones that aren't worth the time rn
