### ISSUE TITLE
Revert name colors to be the same as rank colors

### ISSUE THREAD

**Issue by Pemigrade** [Pemigrade/Acorn#21]
![image](https://user-images.githubusercontent.com/43528123/85985442-5c2c2100-b9b0-11ea-9dd9-a4959d16909a.png)
Revert from 1 to 2

**Comment by vinceingithub** [comment]
I honestly think the white names looks better.

**Comment by Pemigrade** [comment]
OK, looks like most people in #suggestions prefer it too
