### ISSUE TITLE
Update Rules

### ISSUE THREAD

**Issue by Pemigrade** [Pemigrade/Acorn#26]
**Brief Description**
Ban all prefixes in warp names. Warps like /warp !shop or /warp !! would be deleted.

Also, classify bragging about "breaking the economy" under toxicity.

**Why do you want the feature?**
It's annoying that current warp names all start with !, so players need to check if it has a prefix before warping to it.

A lot of players get angry when someone brags about breaking the economy, even though it's impossible... The rule would only be against bragging about it, not actually undercutting or similar actions that players say "break the economy"

**Comment by kakd** [comment]
Wouldn't players then just rename their warps to something like **ashop** or **aashop** or **aaashop**

**Comment by Pemigrade** [comment]
We had the rule on flop, that didn't happen. Using letters counts as a prefix as well, and ashop is less spammy than !shop since ppl call it ashop instead of shop and so users know what to type

**Comment by entwastaken** [comment]
stuff like "ashop" should only be ok if it's clear the warp is meant to be called "a shop". if someone names their warp "anetherite" or  "amending" its obviously a prefix and should be punished

**Comment by Pemigrade** [comment]
I agree with ent

**Comment by Pemigrade** [comment]
Added rules:

Annoying others is not allowed. Bragging about "breaking the economy" is considered a form of annoying other players.

Do not accuse other players of hacking in global chat. Do not joke about using hacks.

Warp names can not begin with a prefix for the purpose of moving it up in the /warp list.

 If a staff member instructs you to end a conversation, you must end it regardless of its controversiality.
