### ISSUE TITLE
Complete the events team

### ISSUE THREAD

**Issue by Pemigrade** [Pemigrade/Acorn#3]
Create an events team

**Comment by Pemigrade** [comment]
being worked on by vince and sonic

**Comment by Sonic-Probe** [comment]
Events discord category set up.  
Events team role formed. 
Events team structure purview and rules formed. 
Initial membership contribution from staff added.

**Comment by manbrodude** [comment]
Events application form finished

**Comment by manbrodude** [comment]
Added [Events] to /warp ranks

**Comment by manbrodude** [comment]
- The [Events] prefix will now show on the events server regardless of rank
- The LP group "events" has operator among many other permissions in context server = events
- The LP group "events" is linked with @events on the discord
- Events team application process restructured (still not public)
- Events leadership restructured
- Events application re-written (still not public)
- Events team related channels set up, permissions synced

**Comment by vinceingithub** [comment]
The following permissions have been assigned to the luckperms group [Events] in the context server = events.
- Imageonmap/maptool commands
- Mapart commands
- Particle picker commands
- /setworldspawn
- All world edit commands
- /ast
- /effect
- /fly
- /vanish
- /gamemode

**Comment by vinceingithub** [comment]
The following permissions have been removed from the luckperms group [Events] in the context server = events.
- Mapart commands

**Comment by kakduman** [comment]
Being completed in #events, managed by the staff team. Might be developed more comprehensively in the future.
