### ISSUE TITLE
Add the wither rank @ 2k votes

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#33]
**Brief Description**
A clear and concise description of what you want to happen.|

At 2k votes a player will get the rank &8&l[Wither] this rank will have an additional /ah slot for a total of 3 and an additional sethome for a total of 6 (more perks can be added later)

**Why do you want the feature?**
The reasons why you want to see the feature implemented.

Incentive for players to continue voting after phantom/a cool rank

**Comment by vinceingithub** [comment]
Can this be marked as done or are you waiting for www.acornmc.org/ranks?

**Comment by vinceingithub** [comment]
Can this be closed or are you waiting for acornmc.org/ranks?

**Comment by vinceingithub** [comment]
I believe this was completed

**Comment by Pemigrade** [comment]
Correct, thanks <3
