### ISSUE TITLE
Re-add DrSleep

### ISSUE THREAD

**Issue by manbrodude** [Pemigrade/Acorn#34]
**Brief Description**

Re-add the DrSleep plugin so that 1 player can skip the night if need be.

**Why do you want the feature?**
The reasons why you want to see the feature implemented.

Everyone seemed to love the plugin and there was no good reason to remove it, it helped people out and allowed them to keep building while avoiding phantoms and mobs.

**Comment by Pemigrade** [comment]
DrSleep uploaded and enabled. Restart required for /nosleep to be a registered command (show up in blue)
