### ISSUE TITLE
/color codes don't work on signs

### ISSUE THREAD

**Issue by manbrodude** [Pemigrade/Acorn#35]
**Describe the bug**

Using color codes like &l or &6 for example do not actually format signs.

**Expected behavior**

If you try to use color codes on signs you should not have the sign be formatted.

**To Reproduce**
1. Get a sign
2. use color codes while writing on it with /color perms
3. hit done and see error

**Comment by Pemigrade** [comment]
Major changes with essentials, including:
- signs now work
- players are now DM'd their coords upon death
- minimum /pay amount is now 0.01
- tpyes accept cancellation increased to 300s
- and more...
