### ISSUE TITLE
Add rare crate keys to vote streaks

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#36]
**Brief Description**

I feel that it would be a good addition to reward people for vote streaks with rare crate keys. My idea is that if you vote 35 times a week (5 votes a day) you'll get a rare crate key on that sunday. If you keep the streak up the key number will increase by +1 per week up until a max of 3 keys. So, if I vote 5 times every day for 3 weeks I'll get 3 vote keys and if I keep it up then every sunday I'll get 3 more keys.

**Why do you want the feature?**
The reasons why you want to see the feature implemented.

Currently, I almost feel like the rare crates are *too* rare for the prizes that they give, this is a good way to balance the system.

**Comment by manbrodude** [comment]
Alt idea: "it should go to 5 and like piglin, if you manage to vote 5 times in a day you get a rare crate key" -vegicide

**Comment by Pemigrade** [comment]
Done, streaks now will give a rare crate key every 5 days and an epic one every 30 days
