### ISSUE TITLE
Villagers zombifying is on

### ISSUE THREAD

**Issue by manbrodude** [Pemigrade/Acorn#40]
**Describe the bug**

Villager zombification is normally turned off to prevent grief, it is now turned on.

**Expected behavior**

A villager should take no damage from undead mobs.

**To Reproduce**
1. Get a villager & zombie
2. Observe error

**Comment by Pemigrade** [comment]
made zombies un-agro'd toward villagers, restart required

**Comment by Pemigrade** [comment]
Tested, can confirm that the issue is resolved.
