### ISSUE TITLE
Helpop and #lounge are not linked

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#42]
**Describe the bug**

Normally helpop messages are sent to #lounge on the discord but for some reason #lounge is linked with server 15's helpop still.

**Expected behavior**

Chats with the command /h should be sent in #lounge

**Comment by Pemigrade** [comment]
https://www.spigotmc.org/resources/discordsrv-staff-chat.44245/

**Comment by Pemigrade** [comment]
Fixed with DrChat
