### ISSUE TITLE
/warp Teams doesn't work as intended

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#47]
**Describe the bug**

When you go to /warp teams and right click a sign, it will say that it added you to a team but if you try to use /tm it will say "You must join a team to use /tm" It will act like it assigns you a team but it does not.

**Expected behavior**

It should add you to a team and that team's color would display above your head and in your death messages as well as allow you to use /tm.

**Comment by Pemigrade** [comment]
Potential merge with #2

**Comment by Pemigrade** [comment]
No more /warp teams
