### ISSUE TITLE
Make the Tab Menu sorted by rank

### ISSUE THREAD

**Issue by Gottiii** [Pemigrade/Acorn#49]
**Brief Description**
Change the sorting in the tab menu from alphabetical to by rank.

**Why do you want the feature?**
It will be easier to see who's online like staff, specific players, etc.

**Comment by Pemigrade** [comment]
Done. This is how it will look after the next restart. I also removed the headers.
![image](https://user-images.githubusercontent.com/43528123/87636736-c9f18000-c706-11ea-8de0-155b80110256.png)
