### ISSUE TITLE
Make jukeboxes lockable

### ISSUE THREAD

**Issue by manbrodude** [Pemigrade/Acorn#51]
**Brief Description**

Please make it so that you can lock jukeboxes with /lock.

**Why do you want the feature?**
The reasons why you want to see the feature implemented.

This feature is needed because as of rn people can steal music discs if you leave them exposed.

**Comment by Pemigrade** [comment]
Done! Restart required.

**Comment by Pemigrade** [comment]
Tested by Vince and gala, able to confirm that it works.
