### ISSUE TITLE
/homes doesn't work like it used to

### ISSUE THREAD

**Issue by manbrodude** [Pemigrade/Acorn#52]
**Describe the bug**

So basically how the command formats used to go were: if you typed *just* /homes it would list all your homes **but** if you typed /homes <homename> **or** /home <home name> both would TP you to that home. It currently does not work like this and as someone who always typed "/homes h" it's annoying to see my homes listed and then recall "oh yeah I have to do /home <home name> only now"

**Expected behavior**

Once fixed saying either /home <home name> or /homes <home name> will tp you to the designated home.

**To Reproduce**

1). do /homes <home name>
2). see error

**Comment by Pemigrade** [comment]
/homes was broken by #4. It now works how it did on 1.15. Restart required.

**Comment by Pemigrade** [comment]
Tested, can confirm that /homes works as intended.
