### ISSUE TITLE
/hdb is broken

### ISSUE THREAD

**Issue by manbrodude** [Pemigrade/Acorn#58]
**Describe the bug**

All heads on the /hdb are steve's skull in every catagory.

**Expected behavior**

/hdb should have a variety of heads in every catagory.

**To Reproduce**
1. do /hdb
2. see error

**Comment by Pemigrade** [comment]
Unable to reproduce.

![image](https://user-images.githubusercontent.com/43528123/86421004-f2f12a00-bc9d-11ea-9f82-41716a37a446.png)
