### ISSUE TITLE
Add donor perks to mods group

### ISSUE THREAD

**Issue by manbrodude** [Pemigrade/Acorn#68]
**Brief Description**

Make it so that the mods group has perms to use all new vote perks

**Why do you want the feature?**

Mods+ normally have all voteperks but the new ones are not included as of right now.

**Comment by Pemigrade** [comment]
What are the new vote perks?

**Comment by manbrodude** [comment]
hex code colors, pets, beezooka, etc, etc

**Comment by Pemigrade** [comment]
Done.
