### ISSUE TITLE
Spam clicking the "next page" button in coreprotect logs makes you get kicked for spamming.

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#69]
**Describe the bug**

If you spam click the little > button on CP logs fast enough you'll get kicked for spam.

**Expected behavior**

This obv isn't spam and shouldn't kick people for it.

**To Reproduce**
1. find some long CP logs
2. spam click the > button
3. see error

**Comment by Pemigrade** [comment]
Fixed as of December 30, 2020 :P
