### ISSUE TITLE
Add "using alts to post more ah listings" under unacceptable uses of alts in the rules.

### ISSUE THREAD

**Issue by manbrodude** [Pemigrade/Acorn#71]
**Brief Description**

Add "you may not use alts to post more ah listings" into the rules under alts.

**Why do you want the feature?**

as it stands it is currently a way to abuse the /ah listing amount.

**Comment by Pemigrade** [comment]
Updated the rules. https://www.acornmc.org/rules#h.p_yNkAnMXT-JPU
