### ISSUE TITLE
Ingame notification of slur usage to staff

### ISSUE THREAD

**Issue by galagami** [Pemigrade/Acorn#73]
**Brief Description**
An ingame notification/warning of whenever a user posts a slur or otherwise automatically deleted word/phrase for staff. 

**Why do you want the feature?**
 If someone were to type out or spam slurs in game and staff isn't looking on Discord, it might go undetected because it's automatically deleted. 

**Additional context**
 The slurs that were used in game got deleted from the chat, however on discord in the global channel they still appeared and it was only brought to attention a bit after it occurred.

**Comment by kakd** [comment]
I have given helpers the permission griefprevention.admin.chat.eavesdrop which allows them to see messages from players who were softmuted and resolves this issue.

**Comment by kakd** [comment]
My fix did not work

**Comment by DrBot7** [comment]
Should be fixed now!
