### ISSUE TITLE
Remove fall damage at spawn

### ISSUE THREAD

**Issue by manbrodude** [Pemigrade/Acorn#76]
**Brief Description**

I want fall damage to be removed in the spawn worldguard region.

**Why do you want the feature?**

As of right now, if you jump off spawn and land on solid ground you can die and loose all your items, that shouldn't happen at the server's spawn.

**Comment by Pemigrade** [comment]
Interesting. You're supposed to be invincible!

**Comment by Pemigrade** [comment]
Unable to reproduce.
