### ISSUE TITLE
Players don't receive notifications from chestshops

### ISSUE THREAD

**Issue by Pemigrade** [Pemigrade/Acorn#81]
**Describe the bug**
Players don't receive notifications from chestshops

**To Reproduce**
1. Create shop
2. Buy from that shop using an alt account
3. See error: owner does not receive notification

**Comment by manbrodude** [comment]
This issue has been resolved. https://github.com/Pemigrade/Acorn/issues/31 still persists, however.

**Comment by Pemigrade** [comment]
Thanks, looks like I forgot to mark as done
