### ISSUE TITLE
Aesthetic improvement to spawn

### ISSUE THREAD

**Issue by LatteOnGithub** [Pemigrade/Acorn#83]
**Brief Description**
Replace the iron bars used for the well near /warp crates with chains.

**Why do you want the feature?**
An actual well would use a chain to pull up buckets used to get water. Now that chains are in the game this can be done.

**Additional context**

**Comment by Pemigrade** [comment]
Fixed this urgent issue immediately, looks like we overlooked 1.16's chains :)
