### ISSUE TITLE
Add a resnether

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#85]
**Brief Description**

Add a resnether and resend that would routinely be reset.

**Why do you want the feature?**

Because this way we can A). have more end cities to keep things like elytras in constant circulation and B). have more piglin bastions/netherite to keep in constant circulation.

**Comment by manbrodude** [comment]
My idea would be that these dimensions would be reset once every 3 months. (Open to change)

**Comment by ndomenic** [comment]
Agreed, this would make end-game items such as elytra and shulker boxes far more accessible to new players coming to the server

**Comment by Pemigrade** [comment]
Definitely planned for the near future. I think the most popular reset option was once every ~4 months.

**Comment by Pemigrade** [comment]
Resnether may be coming soon, I'll do the resend now though :)
