### ISSUE TITLE
Increase the minimum reward in the rare crate. / Primustheone's suggestion

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#86]
**Brief Description**

Multiple rare crate rewards such as EXP and money should be upped in amount. The minimum EXP amount should be 1,000XP and the minimum amount of cash should be $150. (Numbers open to change)

**Why do you want the feature?**

Rare crate keys are so rare that having rewards like this in the rare crate almost feels like a rip off. I can understand wanting a feeling of "luck of the draw" but these rewards are far too low as is.

**Community Approval**

This suggestion has already been approved by the community as it has 12 upvotes in #suggestions ( https://discordapp.com/channels/354802944354418688/540339402526818304/733663017929146418 )

**Comment by Pemigrade** [comment]
Minimum amount of cash will likely be lowered. Minimum XP amount looks good.

**Comment by manbrodude** [comment]
Lowered.. you mean increased?

**Comment by Pemigrade** [comment]
Rare crates now give on average 16x more money than they used to ($16/use -> $256/use)
