### ISSUE TITLE
Add a DND plugin

### ISSUE THREAD

**Issue by Gottiii** [Pemigrade/Acorn#90]
**Brief Description**
Add a plugin like https://dev.bukkit.org/projects/do-not-disturb or something similar, so that any player can do something like /dnd so they appear as though they aren't online, and possibly have it disable chat for them as well so they don't see the chat feed.

**Why do you want the feature?**
It would be helpful for anyone who might want to work on a build, do staff stuff, or work on any project where they wouldn't want to be bothered with people messaging them or the chat blowing up while they focus.

**Comment by manbrodude** [comment]
This could be very useful.

**Comment by Pemigrade** [comment]
Is /togglechat insufficient? It disables chat while allowing whispers.

**Comment by Pemigrade** [comment]
Will be added when https://github.com/MultiChat/Development/issues/132 is completed. Currently impossible.

**Comment by kakduman** [comment]
DND abandoned
