### ISSUE TITLE
Increase entity cramming limit

### ISSUE THREAD

**Issue by LatteOnGithub** [Pemigrade/Acorn#91]
**Brief Description**
Increase maxEntityCramming from 5 to 8-12

**Why do you want the feature?**
This has been requested several times and has not been rejected nor accepted.
Mobs just randomly pathfinding can kill themselves which makes having animals in a pen not viable.
Entity cramming being set to 24 would make creating cramming based killing mechanisms used for gold farms more annoying, increasing it a little is not as big of a deal.

**Comment by Pemigrade** [comment]
maxEntityCramming increased from 5 to 10. It may be decreased to 5 in the future without warning if we experience significant entity lag.
