### ISSUE TITLE
Sabotage: Players don't drop items on death; supposedly you are meant to be able to access their dead body's inventory and loot them, but that does not work.

### ISSUE THREAD

**Issue by entwastaken** [Pemigrade/Acorn#92]
**Describe the bug**
When a player dies in Sabotage, they leave behind a corpse of their skin with their armour, and no longer drop their items upon death. This leads to their items being perma-deleted for the entire round, possibly leaving the Saboteur(s) at a gear disadvantage if they cannot loot their victims. From what I have heard, you are supposed to be able to access their inventory at their corpse and loot them, but that doesn't work either.

**Expected behavior**
Upon a player death, their items would normally burst out of their body like in vanilla, as it did pre-Birdflop-Acorn-merge.

**To Reproduce**
1. Join a game of Sabotage.
2. Kill a player.
3. Observe.

**Comment by Pemigrade** [comment]
Known issue, already fixed. Just required a restart. Restarted now. Long-term plan is to make people drop inventories and be unable to open corpse inventories.
