### ISSUE TITLE
Sabotage: Opening chests sometimes leads to being stuck in place.

### ISSUE THREAD

**Issue by entwastaken** [Pemigrade/Acorn#94]
**Describe the bug**
Opening chests while running can sometimes lead to you being stuck on the block you're standing if you try to run or walk, only being able to move via sneaking until you either: move a certain amount of blocks away from the initial stuck-spot, or a certain amount of time passes. While not necessarily conclusive, from my experience it seems that it usually happens if you have the Speed effect from a potion. This can lead to being unable to run away from the Saboteur while Innocent, or even chase down an Innocent as the Saboteur.

**Expected behavior**
After opening a chest, no movement impairment should occur.

**To Reproduce**
1. Join a Sabotage game
2. (Optional?) Drink a Speed / Speed II potion.
3. While sprinting, open chests.
4. If it worked, you will be stuck in place as if you were using [/afk] back in 1.15 and tried to move off the block you are standing on, unable to leave it.

**Comment by Pemigrade** [comment]
Fixed!
