### ISSUE TITLE
RGB nicks don't work in Sabotage

### ISSUE THREAD

**Issue by entwastaken** [Pemigrade/Acorn#95]
**Describe the bug**
Using RGB codes in /nick will not result in an RGB nickname in Sabotage.

**Expected behavior**
RGB nicks should function as they do in Survival.

**To Reproduce**
1. Go to [/sabotage]
2. Try to set a nick using RGB codes.

**Comment by Pemigrade** [comment]
There is no way to fix the issue. Sabotage is 1.15 since corpses are incompatible with 1.16. It approximates 1.16 RGB colors to 1.15 JSON colors.
