### ISSUE TITLE
Send "[player] is no longer afk" messages in #global

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#96]
**Brief Description**

Make it so the message notifying others that a player is no longer afk is sent in #global

**Why do you want the feature?**

Even if you're not in game it can still be helpful to know who is and isn't afk/how long ago they came back.

**Comment by Pemigrade** [comment]
Previously denied by the community since it could get spammy. The only way to accomplish this would be to broadcast to the Discord that a player is AFK/no longer AFK rather than a discreet message.
