### ISSUE TITLE
Replace the /suicide "Player took their own life" message with the regular "Player died" message

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#97]
**Brief Description**

Make it so that instead of sending the message "Player took their own life" from using /suicide, it says something generic like "Player died" or "Player fell out of the world"

**Why do you want the feature?**

Having the message stay as is seems to always lead to people making suicide jokes or using the command to make suicide jokes (i.e. "'I can't take this anymore' Player took their own life")

**Comment by Pemigrade** [comment]
Thanks for reminding me, done!
