### ISSUE TITLE
Ender dragon does not respawn

### ISSUE THREAD

**Issue by SirOllie** [Pemigrade/Acorn#98]
**Describe the bug**
When placing four end crystals on the portal in the end to summon the dragon, it doesnt summon. Nothing happens at all...

**Expected behavior**
When placing four end crystals on the portal in the end, the dragon should appear.

**To Reproduce**
1. Go to the end portal in the end.
2. Place four end crystals, one on each side (in the middle of the three bedrock blocks in the portal frame)
3. Observe that nothing happens.

**Additional context**
Didnt work for players, and didnt work when I tried to do it (SirOllie)

**Comment by Pemigrade** [comment]
Fixed!
