### ISSUE TITLE
Warped and crimson slabs do not craft into blocks correctly

### ISSUE THREAD

**Issue by LatteOnGithub** [Pemigrade/Acorn#99]
**Describe the bug**
Trying to craft a block from 2 warped/crimson slabs makes one slab.

**Expected behavior**
The recipe results in warped/crimson planks.

**To Reproduce**

![warped](https://user-images.githubusercontent.com/68391310/88210307-a5dcf400-cc5c-11ea-8554-5ca846164926.png)
![crimson](https://user-images.githubusercontent.com/68391310/88210309-a6758a80-cc5c-11ea-9f5c-918b6648d4e5.png)

**Comment by kakd** [comment]
Should be fied after the next restart
